export const SCRIPT_ID = "react-squircle-script";

export const VARIANTS = {
  BACKGROUND_SQUIRCLE_WITH_SHADOW: "bg-sh",
  BACKGROUND_SQUIRCLE_WITH_BACKGROUND_COLOR: "bg-bc",
  BACKGROUND_SQUIRCLE_WITH_BACKGROUND_COLOR_AND_SHADOW: "bg-bc-sh",
  BACKGROUND_SQUIRCLE_WITH_BORDER: "bg-bd",
  BACKGROUND_SQUIRCLE_WITH_BORDER_AND_SHADOW: "bg-bd-sh",
  BACKGROUND_SQUIRCLE_WITH_BORDER_AND_BACKGROUND_COLOR: "bg-bd-bc",
  BACKGROUND_SQUIRCLE_WITH_BORDER_AND_BACKGROUND_COLOR_AND_SHADOW:
    "bg-bd-bc-sh",
  MASK_SQUIRCLE_WITH_BACKGROUND_COLOR: "ms-bc",
  MASK_SQUIRCLE_WITH_BACKGROUND: "ms-bg",
} as const;
